name: default

on:
  push:
    branches:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - run: python /src/attack_nav_mod.py 

    - uses: actions/upload-artifact@v2
      with:
        name: mbc-attack-nav
        path: mbc-attack-nav-modified.json
