name: default

on:
  push:
    branches:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - run: ls
    - run: python ./src/attack_nav_mod.py --mbc-content-location ./mbc/mbc.json
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: mbc-attack-nav-modified.json
